// Auto-generated by _extract-pins.mjs — do not edit by hand.
// Re-generate after README adds new simulation links:
//   node simulations/fast/_extract-pins.mjs
//
// Maps each fast script name to the block_height of the historical UI run
// referenced in the README. Used to pin every fast simulation to a known-good
// block, eliminating chain-state drift (LENDER balance, STX whale balance,
// Pyth feed timing) so the verifier tests contract behavior in isolation.

export const blockPins = {
  "simul-jing-loan-sbtc-stx-single": {
    "block_height": 7680891,
    "block_hash": "54cbe509aac92a6f8f7940c8b2d3118a23be3b3aae6e3b8020e5d6858e360089"
  },
  "simul-jing-loan-seize": {
    "block_height": 7681006,
    "block_hash": "1670dfb5b0acde60a452565934e698d79f461f47fb74aead37b1944c3b88b873"
  },
  "simul-jing-loan-repay-stx": {
    "block_height": 7681069,
    "block_hash": "c9498b5c1ff28063bb31ee9c848a09142ed0760a3cca04230b591617f73d686e"
  },
  "simul-jing-loan-true-happy-path": {
    "block_height": 7681250,
    "block_hash": "ffcbbc2adae48a2538e91a7ae458096d6ed5c24e8864979f74a760b019f1d4b8"
  },
  "simul-jing-loan-rollover": {
    "block_height": 7682523,
    "block_hash": "cf7c5ceae972cab6abfad081833828bba97cc4c262dca480fd8a54fc71a61321"
  },
  "simul-jing-loan-withdraw-funds": {
    "block_height": 7682702,
    "block_hash": "5a7242704108960ad7f33c48ddfff345dec5dca86c9c65e79f99db66ad18481e"
  },
  "simul-jing-loan-errors": {
    "block_height": 7682829,
    "block_hash": "c20ae99a7085f87bf4f9816972849b4ee0e5b338e32cc05c6acd4db4d338f02c"
  },
  "simul-jing-loan-serial": {
    "block_height": 7682967,
    "block_hash": "c850ae524fdde34eac60514409f4339c1eb24d49bc656a05edfcd181e4c961d2"
  },
  "simul-jing-loan-set-swap-limit": {
    "block_height": 7683016,
    "block_hash": "b70db8ebaba2da739dba4a256b102d2bdbcb0085ea989471e603268477879674"
  },
  "simul-jing-loan-admin": {
    "block_height": 7683050,
    "block_hash": "3f687ac18a2a4bbb031ef052dc305606d955fac3ab3a48985bc6eefcc545a057"
  },
  "simul-jing-loan-refund-branch": {
    "block_height": 7683221,
    "block_hash": "4f766e861180486ed821aa5d303b884d5570daedd8c97430c5b2a0b3ec00c387"
  },
  "simul-jing-loan-reborrow-after-seize": {
    "block_height": 7683221,
    "block_hash": "4f766e861180486ed821aa5d303b884d5570daedd8c97430c5b2a0b3ec00c387"
  },
  "simul-loan-snpl-happy": {
    "block_height": 7755437,
    "block_hash": "6cdde1bc2a84ec2f9039b0aefcc327138c315fc1cafe82db99d54903ada2027a"
  },
  "simul-loan-snpl-true-happy": {
    "block_height": 7755851,
    "block_hash": "4e153fb30f138edb6a72b349d72bf5cf9dd3f7961e336050c3991a19849ecb49"
  },
  "simul-loan-snpl-seize": {
    "block_height": 7755660,
    "block_hash": "10bf23ba9c50c0da666350e51285c367e791f112c37f0589ed800fd15ece9eb4"
  },
  "simul-loan-snpl-seize-rolled": {
    "block_height": 7755762,
    "block_hash": "d82689751686e4f0933fdd85b80c3e89bd857c3bf92176028da36dfcad6f1d8a"
  },
  "simul-loan-snpl-multi": {
    "block_height": 7755950,
    "block_hash": "61fb9f0745e68b3eac187fceffc3a3caf022b9ec4151d38a6d6e505f2ebb7531"
  },
  "simul-loan-snpl-set-reserve": {
    "block_height": 7756080,
    "block_hash": "844d4b2a00585fc0450a46d9b6ea35404877989fe2f614bdaa8e57f5898f51bd"
  },
  "simul-loan-snpl-rollover": {
    "block_height": 7756525,
    "block_hash": "af97b75a304c54c5ec6784ee9666106b16626824a8f7d20e71770ce15efa25a8"
  },
  "simul-loan-snpl-reborrow-after-seize": {
    "block_height": 7756525,
    "block_hash": "af97b75a304c54c5ec6784ee9666106b16626824a8f7d20e71770ce15efa25a8"
  },
  "simul-loan-snpl-repay-refund": {
    "block_height": 7756848,
    "block_hash": "b18b3c38b551fbc257ced7a021e7f9a3633b13f486f02b5f61f1cecb073cdbfb"
  },
  "simul-loan-snpl-set-swap-limit": {
    "block_height": 7758257,
    "block_hash": "b05cff6a3456df002ae099bd454654432baae188c80eb3887bc3eb5696444175"
  },
  "simul-loan-snpl-multi-real-settle": {
    "block_height": 7758313,
    "block_hash": "2c71c98c9aa7f2677020fd43ac5133f688db9b542fc97e55b7303eb27e65e781"
  },
  "simul-loan-snpl-redeposit": {
    "block_height": 7758353,
    "block_hash": "9c88127b5d6790d5be812c4170f80c7e605ec596ac395f3fe0b905cb3ef2ded4"
  },
  "simul-loan-snpl-lender-withdraw-mid-loan": {
    "block_height": 7758390,
    "block_hash": "9eed382300fdbf4fdba8d8a9fe0fc02edbb44fc22bbde55e22aa43c808bdc701"
  }
};
