// Auto-generated by _parse-readme.mjs — do not edit by hand.
// Re-generate after README changes: node simulations/fast/_parse-readme.mjs
//
// Maps each fast script name to a sparse map of { stepIdx: expectedClarityString }.
// Entries are pulled from the README "### Steps" tables, only for rows whose
// Result column is a precise Clarity value (e.g. "(ok u1)", "u100", "(err u103)",
// "(some u1)", "none", "true", "false", "Success").
//
// Steps with looser README descriptions (e.g. "status u0 (PRE-SWAP)") are NOT
// in this map — verifier passes them through with hard-fail check only.

export const expectations = {
  "simul-jing-loan-sbtc-stx-single": {
    "0": "Success",
    "1": "(ok true)",
    "2": "u22000000",
    "3": "(ok u1)",
    "4": "(some u1)",
    "6": "(ok u24750000)",
    "7": "u0",
    "8": "(ok true)",
    "10": "u22000000",
    "11": "(ok true)",
    "12": "u0",
    "13": "u22000000",
    "14": "(ok true)",
    "15": "u20001209",
    "16": "(ok true)",
    "18": "none",
    "19": "u0",
    "20": "u0",
    "21": "u25097353"
  },
  "simul-jing-loan-seize": {
    "0": "Success",
    "1": "(ok true)",
    "3": "(ok u1)",
    "6": "(ok true)",
    "9": "(ok true)",
    "11": "u22000000",
    "13": "u5000000000",
    "14": "(ok true)",
    "16": "none",
    "19": "u22347353",
    "20": "u5001000000"
  },
  "simul-jing-loan-withdraw-funds": {
    "2": "(ok true)",
    "4": "(ok true)",
    "6": "(ok true)",
    "8": "(ok true)",
    "10": "(ok u1)",
    "13": "(err u103)",
    "15": "(err u100)",
    "18": "(ok true)",
    "20": "u30000000"
  },
  "simul-jing-loan-set-swap-limit": {
    "9": "(err u101)",
    "11": "(err u105)",
    "15": "(err u106)"
  },
  "simul-jing-loan-admin": {
    "11": "(ok true)",
    "18": "(err u102)",
    "19": "(ok u2)"
  }
};
