// Extract per-script historical block heights by walking each README's
// "Sim N: ... (`simul-foo.js`)" section, capturing the stxer.xyz URL inside,
// and fetching that simulation's metadata to read its block_height.
//
// Output: simulations/fast/_block-pins.js — exported map used by _transform.mjs
// to inject `.useBlockHeight(N)` into each fast script. Pinning eliminates
// chain-state drift so verifier results test contract behavior, not balances.
//
// Re-run when READMEs add new simulation links.

import fs from "node:fs";
import path from "node:path";

const READMES = [
  "simulations/README-stxer-jing-loan.md",
  "simulations/README-stxer-loan-snpl.md",
];

const STXER_API = "https://api.stxer.xyz";

function parseSections(file) {
  const text = fs.readFileSync(file, "utf8");
  const sections = text.split(/^## (?=(?:Simulation|Sim) \d+)/m);
  const result = [];

  for (const section of sections) {
    const headerMatch = section.match(/^(?:Simulation|Sim) \d+:.*?\(`(simul-[a-z0-9-]+)\.js`\)/);
    if (!headerMatch) continue;
    const scriptName = headerMatch[1];

    const idMatch = section.match(/stxer\.xyz\/simulations\/mainnet\/([a-f0-9]+)/);
    if (!idMatch) continue;
    const simId = idMatch[1];

    result.push({ scriptName, simId });
  }
  return result;
}

async function fetchBlockHeight(simId) {
  const url = `${STXER_API}/devtools/v2/simulations/${simId}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`GET ${url} → ${res.status}`);
  const data = await res.json();
  return {
    block_height: data.metadata.block_height,
    block_hash: data.metadata.block_hash,
  };
}

const all = [];
for (const f of READMES) all.push(...parseSections(f));

console.log(`Found ${all.length} (script, simId) pair(s). Fetching metadata...`);

const pins = {};
for (const { scriptName, simId } of all) {
  try {
    const meta = await fetchBlockHeight(simId);
    pins[scriptName] = meta;
    console.log(`  ${scriptName.padEnd(50)} sim ${simId.slice(0, 12)}…  block ${meta.block_height}`);
  } catch (e) {
    console.error(`  ${scriptName}: failed — ${e.message}`);
  }
}

const out = path.resolve("simulations/fast/_block-pins.js");
const body = `// Auto-generated by _extract-pins.mjs — do not edit by hand.
// Re-generate after README adds new simulation links:
//   node simulations/fast/_extract-pins.mjs
//
// Maps each fast script name to the block_height of the historical UI run
// referenced in the README. Used to pin every fast simulation to a known-good
// block, eliminating chain-state drift (LENDER balance, STX whale balance,
// Pyth feed timing) so the verifier tests contract behavior in isolation.

export const blockPins = ${JSON.stringify(pins, null, 2)};
`;
fs.writeFileSync(out, body);
console.log(`\nWrote ${Object.keys(pins).length} pin(s) → ${out}`);
