// Extract per-step expectations from the two stxer READMEs into _expectations.js.
// Walks each "## Simulation N: ... (`simul-...js`)" section, finds tables that
// look like `| Step | Action | Result |`, and captures every row whose Result
// column contains a precise Clarity value we can compare against.
//
// We only keep rows whose Result starts with one of:
//   (ok ...)   (err ...)   (some ...)   none   u<digits>   true   false
// Anything looser ("status u0 (PRE-SWAP)" etc.) is skipped — verifier just
// confirms the step didn't hard-fail for those.

import fs from "node:fs";
import path from "node:path";

const READMES = [
  "simulations/README-stxer-jing-loan.md",
  "simulations/README-stxer-loan-snpl.md",
];

// Patterns we accept as strict-comparable expectations.
// Order matters: more-specific first.
const ACCEPT_PATTERNS = [
  /^`\(ok [^`]+\)`/,
  /^`\(err [^`]+\)`/,
  /^`\(some [^`]+\)`/,
  /^`none`/,
  /^`u\d+`/,
  /^`true`/,
  /^`false`/,
  /^Success\b/i, // deploy ok
];

function extractClarity(resultCell) {
  // Result cell might be: `` `(ok u1)` — loan 1 created, deadline `u945975` ``
  // We want to capture the FIRST backticked Clarity expression that matches our
  // accept list. Skip prose after the first em-dash or comma.
  const trimmed = resultCell.trim();

  // Special-case bare "Success" for deploys (no backticks).
  if (/^Success\b/i.test(trimmed)) return "Success";

  // Try the patterns in order; capture the first matching backticked token.
  for (const re of ACCEPT_PATTERNS) {
    const m = trimmed.match(re);
    if (m) {
      // Strip leading/trailing backticks
      return m[0].replace(/^`|`$/g, "");
    }
  }
  return null;
}

function parseReadme(file) {
  const text = fs.readFileSync(file, "utf8");
  // jing-loan README uses "Simulation N:", snpl README uses "Sim N:". Match both.
  const sections = text.split(/^## (?=(?:Simulation|Sim) \d+|Calibration|Stxer-specific)/m);
  const result = {};

  for (const section of sections) {
    const headerMatch = section.match(/^(?:Simulation|Sim) \d+:.*?\(`(simul-[a-z0-9-]+)\.js`\)/);
    if (!headerMatch) continue;
    const scriptName = headerMatch[1];

    // Find table rows of shape "| <num> | <action> | <result> |"
    const rowRe = /^\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|/gm;
    const expects = {};
    let m;
    while ((m = rowRe.exec(section)) !== null) {
      const stepNum1 = parseInt(m[1], 10);
      const idx0 = stepNum1 - 1; // README is 1-indexed; our verifier is 0-indexed.
      const resultCell = m[3];
      const expected = extractClarity(resultCell);
      if (expected !== null) {
        expects[idx0] = expected;
      }
    }
    if (Object.keys(expects).length > 0) {
      result[scriptName] = expects;
    }
  }
  return result;
}

const all = {};
for (const f of READMES) {
  Object.assign(all, parseReadme(f));
}

const out = path.resolve("simulations/fast/_expectations.js");
const body = `// Auto-generated by _parse-readme.mjs — do not edit by hand.
// Re-generate after README changes: node simulations/fast/_parse-readme.mjs
//
// Maps each fast script name to a sparse map of { stepIdx: expectedClarityString }.
// Entries are pulled from the README "### Steps" tables, only for rows whose
// Result column is a precise Clarity value (e.g. "(ok u1)", "u100", "(err u103)",
// "(some u1)", "none", "true", "false", "Success").
//
// Steps with looser README descriptions (e.g. "status u0 (PRE-SWAP)") are NOT
// in this map — verifier passes them through with hard-fail check only.

export const expectations = ${JSON.stringify(all, null, 2)};
`;
fs.writeFileSync(out, body);

const totalSteps = Object.values(all).reduce((n, m) => n + Object.keys(m).length, 0);
console.log(`Parsed ${Object.keys(all).length} script(s), ${totalSteps} step expectation(s) total → ${out}`);
for (const [name, m] of Object.entries(all)) {
  console.log(`  ${name}: ${Object.keys(m).length} step(s)`);
}
